title: "dreamwhite's blog"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: dreamwhite
theme: minima
header_pages:
  - topbar/aboutme.markdown
  - topbar/contact.markdown
  - topbar/hackintosh.markdown
plugins:
  - jekyll-feed
